---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Configurators:
    - Betaflight Configurator:
        icon: npm.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:82
        description: "version: {{HOMEPAGE_VAR_BETAFLIGHT_VERSION}}"
    - ESC Configurator:
        icon: npm.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:83
        description:
    - Blackbox Log Viewer:
        icon: npm.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:85
        description:
    # - ELRS Configurator:
    #     icon: npm.png
    #     href: http://{{HOMEPAGE_VAR_HOST_IP}}:84
    #     description:

- Files:
    - download the files:
        icon: nginx.png
        href: http://{{HOMEPAGE_VAR_HOST_IP}}:86
        description: "current betaflight {{HOMEPAGE_VAR_BETAFLIGHT_VERSION}}, target {{HOMEPAGE_VAR_BETAFLIGHT_FW_TARGET}}. current Bluejay {{HOMEPAGE_VAR_BLUEJAY_VERSION}}, target {{HOMEPAGE_VAR_BLUEJAY_TARGET}}, PWM {{HOMEPAGE_VAR_BLUEJAY_PWM}} kHz. "
