---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Configurators:
    - Betaflight Configurator:
        icon: npm.png
        href: http://localhost:82
        description: "version: {{HOMEPAGE_VAR_BETAFLIGHT_VERSION}}"
    - ESC Configurator:
        icon: npm.png
        href: http://localhost:83
        description:
    # - ELRS Configurator:
    #     icon: npm.png
    #     href: http://localhost:84
    #     description:

- Files:
    - betaflight firmware:
        icon: file.png
        href: none
        description: "betaflight  {{HOMEPAGE_VAR_BETAFLIGHT_VERSION}}, target {{HOMEPAGE_VAR_BETAFLIGHT_FW_TARGET}}"
    - bluejay firmware:
        icon: file.png
        href: none
        description: "target {{HOMEPAGE_VAR_BLUEJAY_TARGET}}, PWM {{HOMEPAGE_VAR_BLUEJAY_PWM}} kHz"
